version: "3"
services:
  #web
  web:
    image: nginx
    volumes:
      - ".:/app"
      - "./docker-dev/nginx/site.conf:/etc/nginx/conf.d/default.conf"
      - "./docker-dev/php.ini:/usr/local/etc/php/conf.d/custom.ini"
    depends_on:
      - php
    ports:
      - "8000:80"
  php:
    build:
      context: .
      dockerfile: docker-dev/Dockerfile
    volumes:
      - ".:/app"
      - "./docker-dev/php.ini:/usr/local/etc/php/conf.d/custom.ini"
#    depends_on:
#      - db
#  db:
#    image: mariadb
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#    - "3307:3306"
